# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slog',
            new_name='slug',
        ),
    ]
