version: '3'

volumes:
  data:

networks: 
  database:
  web:
  queue:

services:
  db: 
    image: postgres:9.6
    volumes:
      # data volume
      - data:/var/lib/postgresql/data
      # scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - database

  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # nginx configuration
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app

  app:
    image: python:3.6
    volumes:
      # Application
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    environment: 
      # - DB_NAME=email_sender
      - DB_NAME=wrong
    networks: 
      - database
      - web
      - queue
    depends_on: 
      - db
      - queue

  queue:
    image: redis:3.2
    networks: 
      - queue
  
  worker:
    build: worker
    volumes:
      # worker
      - ./worker:/worker
    working_dir: /worker
    command: ./worker.py
    networks: 
      - queue
    depends_on: 
      - queue
